# Generated by Django 2.1.2 on 2018-10-29 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=200)),
                ('beskrivelse', models.TextField()),
                ('klassetrin', models.IntegerField()),
                ('oprettet', models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 29, 18, 21, 51, 745981))),
            ],
        ),
        migrations.DeleteModel(
            name='Stylesheets',
        ),
    ]
