# Generated by Django 2.1.2 on 2018-10-29 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181029_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projekter',
            old_name='navn',
            new_name='titel',
        ),
        migrations.AlterField(
            model_name='projekter',
            name='oprettet',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 29, 18, 30, 18, 444541)),
        ),
    ]
