# Generated by Django 2.1.2 on 2018-10-29 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20181029_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projekter',
            options={'verbose_name_plural': 'Projekter'},
        ),
        migrations.RenameField(
            model_name='projekter',
            old_name='titel',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='projekter',
            name='oprettet',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 29, 18, 39, 21, 657076)),
        ),
    ]
