# Generated by Django 2.1.2 on 2018-11-03 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20181029_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekter',
            name='media',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='projekter',
            name='oprettet',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 3, 12, 32, 7, 940944)),
        ),
    ]
