# Generated by Django 2.1.2 on 2018-11-03 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20181103_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekter',
            name='oprettet',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 3, 11, 38, 19, 861069, tzinfo=utc)),
        ),
    ]
