# Generated by Django 2.1.2 on 2018-11-03 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20181103_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekter',
            name='oprettet',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 3, 11, 45, 6, 409174, tzinfo=utc)),
        ),
    ]
