# Generated by Django 2.1.2 on 2018-11-03 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20181103_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekter',
            name='oprettet',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 3, 13, 18, 53, 1970, tzinfo=utc)),
        ),
    ]
