# Generated by Django 2.1.2 on 2018-11-03 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20181103_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekter',
            name='media',
            field=models.FileField(upload_to='project_files   /'),
        ),
        migrations.AlterField(
            model_name='projekter',
            name='oprettet',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 3, 13, 44, 33, 668792, tzinfo=utc)),
        ),
    ]
