# Generated by Django 2.1.2 on 2018-11-03 13:53

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20181103_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projekter',
            name='media',
        ),
        migrations.AddField(
            model_name='projekter',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='project_files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projekter',
            name='oprettet',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 3, 13, 53, 35, 562606, tzinfo=utc)),
        ),
    ]
