# Generated by Django 2.1.2 on 2018-11-03 14:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20181103_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projekter',
            options={'verbose_name': 'Projekt', 'verbose_name_plural': 'Projekter'},
        ),
        migrations.AlterField(
            model_name='projekter',
            name='oprettet',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 3, 14, 56, 40, 10448, tzinfo=utc)),
        ),
    ]
