# Generated by Django 2.1.2 on 2018-11-03 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20181103_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekter',
            name='img_code',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projekter',
            name='img_looks',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projekter',
            name='oprettet',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 3, 17, 6, 13, 216743, tzinfo=utc)),
        ),
    ]
