# Generated by Django 2.1.2 on 2019-02-07 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20181103_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekter',
            name='oprettet',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
