# Generated by Django 2.1.2 on 2019-02-07 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tekster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel_lix', models.CharField(max_length=200)),
                ('beskrivelse_lix', models.TextField()),
                ('lixtal', models.IntegerField()),
                ('punktummer', models.IntegerField()),
                ('antalSaetninger', models.IntegerField()),
                ('avgLength', models.IntegerField()),
                ('klassetrin_lix', models.IntegerField()),
                ('mestBrugteOrd', models.CharField(max_length=200)),
                ('oprettet_lix', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tekst',
                'verbose_name_plural': 'Tekster',
            },
        ),
    ]
