# Generated by Django 2.1.2 on 2019-02-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LixCalc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tekster',
            old_name='titel_lix',
            new_name='title_lix',
        ),
        migrations.AddField(
            model_name='tekster',
            name='forfatter',
            field=models.CharField(default='Jacob Skadborg', max_length=100),
        ),
        migrations.AddField(
            model_name='tekster',
            name='tekst',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
